/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcademicUnitRequest
 */
export interface AcademicUnitRequest {
    /**
     * 
     * @type {string}
     * @memberof AcademicUnitRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AcademicUnitRequest
     */
    sede: string;
}

/**
 * Check if a given object implements the AcademicUnitRequest interface.
 */
export function instanceOfAcademicUnitRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "sede" in value;

    return isInstance;
}

export function AcademicUnitRequestFromJSON(json: any): AcademicUnitRequest {
    return AcademicUnitRequestFromJSONTyped(json, false);
}

export function AcademicUnitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicUnitRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'sede': json['sede'],
    };
}

export function AcademicUnitRequestToJSON(value?: AcademicUnitRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'sede': value.sede,
    };
}

