/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcademicYear
 */
export interface AcademicYear {
    /**
     * 
     * @type {number}
     * @memberof AcademicYear
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof AcademicYear
     */
    year: number;
    /**
     * 
     * @type {Date}
     * @memberof AcademicYear
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof AcademicYear
     */
    end: Date;
}

/**
 * Check if a given object implements the AcademicYear interface.
 */
export function instanceOfAcademicYear(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "year" in value;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "end" in value;

    return isInstance;
}

export function AcademicYearFromJSON(json: any): AcademicYear {
    return AcademicYearFromJSONTyped(json, false);
}

export function AcademicYearFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicYear {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'year': json['year'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
    };
}

export function AcademicYearToJSON(value?: AcademicYear | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year': value.year,
        'start': (value.start.toISOString().substring(0,10)),
        'end': (value.end.toISOString().substring(0,10)),
    };
}

