/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcademicYearRequest
 */
export interface AcademicYearRequest {
    /**
     * 
     * @type {number}
     * @memberof AcademicYearRequest
     */
    year: number;
    /**
     * 
     * @type {Date}
     * @memberof AcademicYearRequest
     */
    start: Date;
    /**
     * 
     * @type {Date}
     * @memberof AcademicYearRequest
     */
    end: Date;
}

/**
 * Check if a given object implements the AcademicYearRequest interface.
 */
export function instanceOfAcademicYearRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "year" in value;
    isInstance = isInstance && "start" in value;
    isInstance = isInstance && "end" in value;

    return isInstance;
}

export function AcademicYearRequestFromJSON(json: any): AcademicYearRequest {
    return AcademicYearRequestFromJSONTyped(json, false);
}

export function AcademicYearRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicYearRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'year': json['year'],
        'start': (new Date(json['start'])),
        'end': (new Date(json['end'])),
    };
}

export function AcademicYearRequestToJSON(value?: AcademicYearRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year': value.year,
        'start': (value.start.toISOString().substring(0,10)),
        'end': (value.end.toISOString().substring(0,10)),
    };
}

