/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcademicUnit
 */
export interface AcademicUnit {
    /**
     * 
     * @type {number}
     * @memberof AcademicUnit
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof AcademicUnit
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AcademicUnit
     */
    sede: string;
}

/**
 * Check if a given object implements the AcademicUnit interface.
 */
export function instanceOfAcademicUnit(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "sede" in value;

    return isInstance;
}

export function AcademicUnitFromJSON(json: any): AcademicUnit {
    return AcademicUnitFromJSONTyped(json, false);
}

export function AcademicUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcademicUnit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'sede': json['sede'],
    };
}

export function AcademicUnitToJSON(value?: AcademicUnit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'sede': value.sede,
    };
}

