/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AreaRequest
 */
export interface AreaRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof AreaRequest
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof AreaRequest
     */
    name: string;
}

/**
 * Check if a given object implements the AreaRequest interface.
 */
export function instanceOfAreaRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function AreaRequestFromJSON(json: any): AreaRequest {
    return AreaRequestFromJSONTyped(json, false);
}

export function AreaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AreaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': json['tags'],
        'name': json['name'],
    };
}

export function AreaRequestToJSON(value?: AreaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags,
        'name': value.name,
    };
}

