/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Area
 */
export interface Area {
    /**
     * 
     * @type {number}
     * @memberof Area
     */
    readonly id: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Area
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Area
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof Area
     */
    readonly postulations: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Area
     */
    readonly users: Array<number>;
}

/**
 * Check if a given object implements the Area interface.
 */
export function instanceOfArea(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "postulations" in value;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function AreaFromJSON(json: any): Area {
    return AreaFromJSONTyped(json, false);
}

export function AreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Area {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tags': json['tags'],
        'name': json['name'],
        'postulations': json['postulations'],
        'users': json['users'],
    };
}

export function AreaToJSON(value?: Area | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags,
        'name': value.name,
    };
}

