/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadRefreshToken
 */
export interface BadRefreshToken {
    /**
     * 
     * @type {string}
     * @memberof BadRefreshToken
     */
    detail: string;
    /**
     * 
     * @type {string}
     * @memberof BadRefreshToken
     */
    code: string;
}

/**
 * Check if a given object implements the BadRefreshToken interface.
 */
export function instanceOfBadRefreshToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "detail" in value;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function BadRefreshTokenFromJSON(json: any): BadRefreshToken {
    return BadRefreshTokenFromJSONTyped(json, false);
}

export function BadRefreshTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRefreshToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'detail': json['detail'],
        'code': json['code'],
    };
}

export function BadRefreshTokenToJSON(value?: BadRefreshToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'detail': value.detail,
        'code': value.code,
    };
}

