/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BadToken,
    instanceOfBadToken,
    BadTokenFromJSON,
    BadTokenFromJSONTyped,
    BadTokenToJSON,
} from './BadToken';
import {
    EmailNotValid,
    instanceOfEmailNotValid,
    EmailNotValidFromJSON,
    EmailNotValidFromJSONTyped,
    EmailNotValidToJSON,
} from './EmailNotValid';

/**
 * @type BadRequest
 * 
 * @export
 */
export type BadRequest = BadToken | EmailNotValid;

export function BadRequestFromJSON(json: any): BadRequest {
    return BadRequestFromJSONTyped(json, false);
}

export function BadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BadTokenFromJSONTyped(json, true), ...EmailNotValidFromJSONTyped(json, true) };
}

export function BadRequestToJSON(value?: BadRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfBadToken(value)) {
        return BadTokenToJSON(value as BadToken);
    }
    if (instanceOfEmailNotValid(value)) {
        return EmailNotValidToJSON(value as EmailNotValid);
    }

    return {};
}

