/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadTutorUserSchedule } from './ReadTutorUserSchedule';
import {
    ReadTutorUserScheduleFromJSON,
    ReadTutorUserScheduleFromJSONTyped,
    ReadTutorUserScheduleToJSON,
} from './ReadTutorUserSchedule';
import type { SearchTutorship } from './SearchTutorship';
import {
    SearchTutorshipFromJSON,
    SearchTutorshipFromJSONTyped,
    SearchTutorshipToJSON,
} from './SearchTutorship';

/**
 * 
 * @export
 * @interface BusquedaTutoriaHorarios
 */
export interface BusquedaTutoriaHorarios {
    /**
     * 
     * @type {Array<ReadTutorUserSchedule>}
     * @memberof BusquedaTutoriaHorarios
     */
    schedules: Array<ReadTutorUserSchedule>;
    /**
     * 
     * @type {Array<SearchTutorship>}
     * @memberof BusquedaTutoriaHorarios
     */
    tutorshipInstances: Array<SearchTutorship>;
}

/**
 * Check if a given object implements the BusquedaTutoriaHorarios interface.
 */
export function instanceOfBusquedaTutoriaHorarios(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "schedules" in value;
    isInstance = isInstance && "tutorshipInstances" in value;

    return isInstance;
}

export function BusquedaTutoriaHorariosFromJSON(json: any): BusquedaTutoriaHorarios {
    return BusquedaTutoriaHorariosFromJSONTyped(json, false);
}

export function BusquedaTutoriaHorariosFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusquedaTutoriaHorarios {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schedules': ((json['schedules'] as Array<any>).map(ReadTutorUserScheduleFromJSON)),
        'tutorshipInstances': ((json['tutorship_instances'] as Array<any>).map(SearchTutorshipFromJSON)),
    };
}

export function BusquedaTutoriaHorariosToJSON(value?: BusquedaTutoriaHorarios | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schedules': ((value.schedules as Array<any>).map(ReadTutorUserScheduleToJSON)),
        'tutorship_instances': ((value.tutorshipInstances as Array<any>).map(SearchTutorshipToJSON)),
    };
}

