/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Career
 */
export interface Career {
    /**
     * 
     * @type {number}
     * @memberof Career
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Career
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Career
     */
    academicUnit: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof Career
     */
    readonly areas: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof Career
     */
    readonly users: Array<number>;
}

/**
 * Check if a given object implements the Career interface.
 */
export function instanceOfCareer(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "academicUnit" in value;
    isInstance = isInstance && "areas" in value;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function CareerFromJSON(json: any): Career {
    return CareerFromJSONTyped(json, false);
}

export function CareerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Career {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'academicUnit': json['academic_unit'],
        'areas': json['areas'],
        'users': json['users'],
    };
}

export function CareerToJSON(value?: Career | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'academic_unit': value.academicUnit,
    };
}

