/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareerXAreaRequest
 */
export interface CareerXAreaRequest {
    /**
     * 
     * @type {number}
     * @memberof CareerXAreaRequest
     */
    career: number;
    /**
     * 
     * @type {number}
     * @memberof CareerXAreaRequest
     */
    area: number;
}

/**
 * Check if a given object implements the CareerXAreaRequest interface.
 */
export function instanceOfCareerXAreaRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "career" in value;
    isInstance = isInstance && "area" in value;

    return isInstance;
}

export function CareerXAreaRequestFromJSON(json: any): CareerXAreaRequest {
    return CareerXAreaRequestFromJSONTyped(json, false);
}

export function CareerXAreaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerXAreaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'career': json['career'],
        'area': json['area'],
    };
}

export function CareerXAreaRequestToJSON(value?: CareerXAreaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'career': value.career,
        'area': value.area,
    };
}

