/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareerRequest
 */
export interface CareerRequest {
    /**
     * 
     * @type {string}
     * @memberof CareerRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CareerRequest
     */
    academicUnit: number;
}

/**
 * Check if a given object implements the CareerRequest interface.
 */
export function instanceOfCareerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "academicUnit" in value;

    return isInstance;
}

export function CareerRequestFromJSON(json: any): CareerRequest {
    return CareerRequestFromJSONTyped(json, false);
}

export function CareerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'academicUnit': json['academic_unit'],
    };
}

export function CareerRequestToJSON(value?: CareerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'academic_unit': value.academicUnit,
    };
}

