/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CareerXArea
 */
export interface CareerXArea {
    /**
     * 
     * @type {number}
     * @memberof CareerXArea
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof CareerXArea
     */
    career: number;
    /**
     * 
     * @type {number}
     * @memberof CareerXArea
     */
    area: number;
}

/**
 * Check if a given object implements the CareerXArea interface.
 */
export function instanceOfCareerXArea(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "career" in value;
    isInstance = isInstance && "area" in value;

    return isInstance;
}

export function CareerXAreaFromJSON(json: any): CareerXArea {
    return CareerXAreaFromJSONTyped(json, false);
}

export function CareerXAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CareerXArea {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'career': json['career'],
        'area': json['area'],
    };
}

export function CareerXAreaToJSON(value?: CareerXArea | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'career': value.career,
        'area': value.area,
    };
}

