/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDeleteTutorUserScheduleRequest
 */
export interface CreateDeleteTutorUserScheduleRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateDeleteTutorUserScheduleRequest
     */
    modality: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeleteTutorUserScheduleRequest
     */
    day: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeleteTutorUserScheduleRequest
     */
    begin: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDeleteTutorUserScheduleRequest
     */
    end: string;
    /**
     * 
     * @type {number}
     * @memberof CreateDeleteTutorUserScheduleRequest
     */
    capacity: number;
    /**
     * 
     * @type {number}
     * @memberof CreateDeleteTutorUserScheduleRequest
     */
    tutorUser: number;
}

/**
 * Check if a given object implements the CreateDeleteTutorUserScheduleRequest interface.
 */
export function instanceOfCreateDeleteTutorUserScheduleRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "modality" in value;
    isInstance = isInstance && "day" in value;
    isInstance = isInstance && "begin" in value;
    isInstance = isInstance && "end" in value;
    isInstance = isInstance && "capacity" in value;
    isInstance = isInstance && "tutorUser" in value;

    return isInstance;
}

export function CreateDeleteTutorUserScheduleRequestFromJSON(json: any): CreateDeleteTutorUserScheduleRequest {
    return CreateDeleteTutorUserScheduleRequestFromJSONTyped(json, false);
}

export function CreateDeleteTutorUserScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDeleteTutorUserScheduleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modality': json['modality'],
        'day': json['day'],
        'begin': json['begin'],
        'end': json['end'],
        'capacity': json['capacity'],
        'tutorUser': json['tutor_user'],
    };
}

export function CreateDeleteTutorUserScheduleRequestToJSON(value?: CreateDeleteTutorUserScheduleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'modality': value.modality,
        'day': value.day,
        'begin': value.begin,
        'end': value.end,
        'capacity': value.capacity,
        'tutor_user': value.tutorUser,
    };
}

