/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailNotValid
 */
export interface EmailNotValid {
    /**
     * 
     * @type {Array<string>}
     * @memberof EmailNotValid
     */
    email: Array<string>;
}

/**
 * Check if a given object implements the EmailNotValid interface.
 */
export function instanceOfEmailNotValid(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function EmailNotValidFromJSON(json: any): EmailNotValid {
    return EmailNotValidFromJSONTyped(json, false);
}

export function EmailNotValidFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailNotValid {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EmailNotValidToJSON(value?: EmailNotValid | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

