/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GoogleAccessTokenRequest
 */
export interface GoogleAccessTokenRequest {
    /**
     * The JWT token obtained from Google.
     * @type {string}
     * @memberof GoogleAccessTokenRequest
     */
    token: string;
}

/**
 * Check if a given object implements the GoogleAccessTokenRequest interface.
 */
export function instanceOfGoogleAccessTokenRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;

    return isInstance;
}

export function GoogleAccessTokenRequestFromJSON(json: any): GoogleAccessTokenRequest {
    return GoogleAccessTokenRequestFromJSONTyped(json, false);
}

export function GoogleAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleAccessTokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function GoogleAccessTokenRequestToJSON(value?: GoogleAccessTokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

