/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoSearchString
 */
export interface NoSearchString {
    /**
     * 
     * @type {string}
     * @memberof NoSearchString
     */
    message: string;
}

/**
 * Check if a given object implements the NoSearchString interface.
 */
export function instanceOfNoSearchString(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function NoSearchStringFromJSON(json: any): NoSearchString {
    return NoSearchStringFromJSONTyped(json, false);
}

export function NoSearchStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoSearchString {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function NoSearchStringToJSON(value?: NoSearchString | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

