/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCreateDeleteTutorUserScheduleRequest
 */
export interface PatchedCreateDeleteTutorUserScheduleRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedCreateDeleteTutorUserScheduleRequest
     */
    modality?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCreateDeleteTutorUserScheduleRequest
     */
    day?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCreateDeleteTutorUserScheduleRequest
     */
    begin?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCreateDeleteTutorUserScheduleRequest
     */
    end?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedCreateDeleteTutorUserScheduleRequest
     */
    capacity?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedCreateDeleteTutorUserScheduleRequest
     */
    tutorUser?: number;
}

/**
 * Check if a given object implements the PatchedCreateDeleteTutorUserScheduleRequest interface.
 */
export function instanceOfPatchedCreateDeleteTutorUserScheduleRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedCreateDeleteTutorUserScheduleRequestFromJSON(json: any): PatchedCreateDeleteTutorUserScheduleRequest {
    return PatchedCreateDeleteTutorUserScheduleRequestFromJSONTyped(json, false);
}

export function PatchedCreateDeleteTutorUserScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCreateDeleteTutorUserScheduleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modality': !exists(json, 'modality') ? undefined : json['modality'],
        'day': !exists(json, 'day') ? undefined : json['day'],
        'begin': !exists(json, 'begin') ? undefined : json['begin'],
        'end': !exists(json, 'end') ? undefined : json['end'],
        'capacity': !exists(json, 'capacity') ? undefined : json['capacity'],
        'tutorUser': !exists(json, 'tutor_user') ? undefined : json['tutor_user'],
    };
}

export function PatchedCreateDeleteTutorUserScheduleRequestToJSON(value?: PatchedCreateDeleteTutorUserScheduleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'modality': value.modality,
        'day': value.day,
        'begin': value.begin,
        'end': value.end,
        'capacity': value.capacity,
        'tutor_user': value.tutorUser,
    };
}

