/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTagRequest
 */
export interface PatchedTagRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedTagRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedTagRequest
     */
    area?: number;
}

/**
 * Check if a given object implements the PatchedTagRequest interface.
 */
export function instanceOfPatchedTagRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTagRequestFromJSON(json: any): PatchedTagRequest {
    return PatchedTagRequestFromJSONTyped(json, false);
}

export function PatchedTagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTagRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'area': !exists(json, 'area') ? undefined : json['area'],
    };
}

export function PatchedTagRequestToJSON(value?: PatchedTagRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'area': value.area,
    };
}

