/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUserRequest
 */
export interface PatchedUserRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserRequest
     */
    uccKey?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUserRequest
     */
    profilePicture?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserRequest
     */
    academicYear?: number;
}

/**
 * Check if a given object implements the PatchedUserRequest interface.
 */
export function instanceOfPatchedUserRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUserRequestFromJSON(json: any): PatchedUserRequest {
    return PatchedUserRequestFromJSONTyped(json, false);
}

export function PatchedUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uccKey': !exists(json, 'ucc_key') ? undefined : json['ucc_key'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'profilePicture': !exists(json, 'profile_picture') ? undefined : json['profile_picture'],
        'academicYear': !exists(json, 'academic_year') ? undefined : json['academic_year'],
    };
}

export function PatchedUserRequestToJSON(value?: PatchedUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ucc_key': value.uccKey,
        'email': value.email,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'profile_picture': value.profilePicture,
        'academic_year': value.academicYear,
    };
}

