/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedRoleRequest
 */
export interface PatchedRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedRoleRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the PatchedRoleRequest interface.
 */
export function instanceOfPatchedRoleRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedRoleRequestFromJSON(json: any): PatchedRoleRequest {
    return PatchedRoleRequestFromJSONTyped(json, false);
}

export function PatchedRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRoleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function PatchedRoleRequestToJSON(value?: PatchedRoleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'type': value.type,
        'description': value.description,
    };
}

