/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUserXTutorshipInstanceXRoleRequest
 */
export interface PatchedUserXTutorshipInstanceXRoleRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserXTutorshipInstanceXRoleRequest
     */
    user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserXTutorshipInstanceXRoleRequest
     */
    tutorshipInstance?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserXTutorshipInstanceXRoleRequest
     */
    role?: number;
}

/**
 * Check if a given object implements the PatchedUserXTutorshipInstanceXRoleRequest interface.
 */
export function instanceOfPatchedUserXTutorshipInstanceXRoleRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUserXTutorshipInstanceXRoleRequestFromJSON(json: any): PatchedUserXTutorshipInstanceXRoleRequest {
    return PatchedUserXTutorshipInstanceXRoleRequestFromJSONTyped(json, false);
}

export function PatchedUserXTutorshipInstanceXRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserXTutorshipInstanceXRoleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : json['user'],
        'tutorshipInstance': !exists(json, 'tutorship_instance') ? undefined : json['tutorship_instance'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function PatchedUserXTutorshipInstanceXRoleRequestToJSON(value?: PatchedUserXTutorshipInstanceXRoleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
        'tutorship_instance': value.tutorshipInstance,
        'role': value.role,
    };
}

