/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedAreaRequest
 */
export interface PatchedAreaRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchedAreaRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchedAreaRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the PatchedAreaRequest interface.
 */
export function instanceOfPatchedAreaRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedAreaRequestFromJSON(json: any): PatchedAreaRequest {
    return PatchedAreaRequestFromJSONTyped(json, false);
}

export function PatchedAreaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAreaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedAreaRequestToJSON(value?: PatchedAreaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags,
        'name': value.name,
    };
}

