/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedPostulationRequest
 */
export interface PatchedPostulationRequest {
    /**
     * 
     * @type {Date}
     * @memberof PatchedPostulationRequest
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedPostulationRequest
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedPostulationRequest
     */
    studentUser?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPostulationRequest
     */
    coordinatorUser?: number;
}

/**
 * Check if a given object implements the PatchedPostulationRequest interface.
 */
export function instanceOfPatchedPostulationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedPostulationRequestFromJSON(json: any): PatchedPostulationRequest {
    return PatchedPostulationRequestFromJSONTyped(json, false);
}

export function PatchedPostulationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPostulationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
        'studentUser': !exists(json, 'student_user') ? undefined : json['student_user'],
        'coordinatorUser': !exists(json, 'coordinator_user') ? undefined : json['coordinator_user'],
    };
}

export function PatchedPostulationRequestToJSON(value?: PatchedPostulationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'status': value.status,
        'student_user': value.studentUser,
        'coordinator_user': value.coordinatorUser,
    };
}

