/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUserXAreaRequest
 */
export interface PatchedUserXAreaRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserXAreaRequest
     */
    user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserXAreaRequest
     */
    area?: number;
}

/**
 * Check if a given object implements the PatchedUserXAreaRequest interface.
 */
export function instanceOfPatchedUserXAreaRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUserXAreaRequestFromJSON(json: any): PatchedUserXAreaRequest {
    return PatchedUserXAreaRequestFromJSONTyped(json, false);
}

export function PatchedUserXAreaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserXAreaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : json['user'],
        'area': !exists(json, 'area') ? undefined : json['area'],
    };
}

export function PatchedUserXAreaRequestToJSON(value?: PatchedUserXAreaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
        'area': value.area,
    };
}

