/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTutorshipInstanceRequest
 */
export interface PatchedTutorshipInstanceRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedTutorshipInstanceRequest
     */
    area?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedTutorshipInstanceRequest
     */
    schedule?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTutorshipInstanceRequest
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedTutorshipInstanceRequest
     */
    status?: string;
}

/**
 * Check if a given object implements the PatchedTutorshipInstanceRequest interface.
 */
export function instanceOfPatchedTutorshipInstanceRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTutorshipInstanceRequestFromJSON(json: any): PatchedTutorshipInstanceRequest {
    return PatchedTutorshipInstanceRequestFromJSONTyped(json, false);
}

export function PatchedTutorshipInstanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTutorshipInstanceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'area': !exists(json, 'area') ? undefined : json['area'],
        'schedule': !exists(json, 'schedule') ? undefined : json['schedule'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function PatchedTutorshipInstanceRequestToJSON(value?: PatchedTutorshipInstanceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'area': value.area,
        'schedule': value.schedule,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
        'status': value.status,
    };
}

