/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedUserXRoleRequest
 */
export interface PatchedUserXRoleRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedUserXRoleRequest
     */
    user?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedUserXRoleRequest
     */
    role?: number;
}

/**
 * Check if a given object implements the PatchedUserXRoleRequest interface.
 */
export function instanceOfPatchedUserXRoleRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUserXRoleRequestFromJSON(json: any): PatchedUserXRoleRequest {
    return PatchedUserXRoleRequestFromJSONTyped(json, false);
}

export function PatchedUserXRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUserXRoleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : json['user'],
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function PatchedUserXRoleRequestToJSON(value?: PatchedUserXRoleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
        'role': value.role,
    };
}

