/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedTutorUserReviewRequest
 */
export interface PatchedTutorUserReviewRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedTutorUserReviewRequest
     */
    comment?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedTutorUserReviewRequest
     */
    occurred?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedTutorUserReviewRequest
     */
    absent?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedTutorUserReviewRequest
     */
    utility?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTutorUserReviewRequest
     */
    tutorUser?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTutorUserReviewRequest
     */
    studentUser?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTutorUserReviewRequest
     */
    tutorshipInstance?: number;
}

/**
 * Check if a given object implements the PatchedTutorUserReviewRequest interface.
 */
export function instanceOfPatchedTutorUserReviewRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedTutorUserReviewRequestFromJSON(json: any): PatchedTutorUserReviewRequest {
    return PatchedTutorUserReviewRequestFromJSONTyped(json, false);
}

export function PatchedTutorUserReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTutorUserReviewRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'occurred': !exists(json, 'occurred') ? undefined : json['occurred'],
        'absent': !exists(json, 'absent') ? undefined : json['absent'],
        'utility': !exists(json, 'utility') ? undefined : json['utility'],
        'tutorUser': !exists(json, 'tutor_user') ? undefined : json['tutor_user'],
        'studentUser': !exists(json, 'student_user') ? undefined : json['student_user'],
        'tutorshipInstance': !exists(json, 'tutorship_instance') ? undefined : json['tutorship_instance'],
    };
}

export function PatchedTutorUserReviewRequestToJSON(value?: PatchedTutorUserReviewRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'occurred': value.occurred,
        'absent': value.absent,
        'utility': value.utility,
        'tutor_user': value.tutorUser,
        'student_user': value.studentUser,
        'tutorship_instance': value.tutorshipInstance,
    };
}

