/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedPostulationXAreaRequest
 */
export interface PatchedPostulationXAreaRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedPostulationXAreaRequest
     */
    postulation?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedPostulationXAreaRequest
     */
    area?: number;
}

/**
 * Check if a given object implements the PatchedPostulationXAreaRequest interface.
 */
export function instanceOfPatchedPostulationXAreaRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedPostulationXAreaRequestFromJSON(json: any): PatchedPostulationXAreaRequest {
    return PatchedPostulationXAreaRequestFromJSONTyped(json, false);
}

export function PatchedPostulationXAreaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedPostulationXAreaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'postulation': !exists(json, 'postulation') ? undefined : json['postulation'],
        'area': !exists(json, 'area') ? undefined : json['area'],
    };
}

export function PatchedPostulationXAreaRequestToJSON(value?: PatchedPostulationXAreaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postulation': value.postulation,
        'area': value.area,
    };
}

