/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCareerXUserRequest
 */
export interface PatchedCareerXUserRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedCareerXUserRequest
     */
    career?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedCareerXUserRequest
     */
    user?: number;
}

/**
 * Check if a given object implements the PatchedCareerXUserRequest interface.
 */
export function instanceOfPatchedCareerXUserRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedCareerXUserRequestFromJSON(json: any): PatchedCareerXUserRequest {
    return PatchedCareerXUserRequestFromJSONTyped(json, false);
}

export function PatchedCareerXUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCareerXUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'career': !exists(json, 'career') ? undefined : json['career'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function PatchedCareerXUserRequestToJSON(value?: PatchedCareerXUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'career': value.career,
        'user': value.user,
    };
}

