/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostulationXArea
 */
export interface PostulationXArea {
    /**
     * 
     * @type {number}
     * @memberof PostulationXArea
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof PostulationXArea
     */
    postulation: number;
    /**
     * 
     * @type {number}
     * @memberof PostulationXArea
     */
    area: number;
}

/**
 * Check if a given object implements the PostulationXArea interface.
 */
export function instanceOfPostulationXArea(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "postulation" in value;
    isInstance = isInstance && "area" in value;

    return isInstance;
}

export function PostulationXAreaFromJSON(json: any): PostulationXArea {
    return PostulationXAreaFromJSONTyped(json, false);
}

export function PostulationXAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostulationXArea {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'postulation': json['postulation'],
        'area': json['area'],
    };
}

export function PostulationXAreaToJSON(value?: PostulationXArea | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'postulation': value.postulation,
        'area': value.area,
    };
}

