/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Postulation
 */
export interface Postulation {
    /**
     * 
     * @type {number}
     * @memberof Postulation
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Postulation
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof Postulation
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof Postulation
     */
    studentUser: number;
    /**
     * 
     * @type {number}
     * @memberof Postulation
     */
    coordinatorUser: number;
}

/**
 * Check if a given object implements the Postulation interface.
 */
export function instanceOfPostulation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "studentUser" in value;
    isInstance = isInstance && "coordinatorUser" in value;

    return isInstance;
}

export function PostulationFromJSON(json: any): Postulation {
    return PostulationFromJSONTyped(json, false);
}

export function PostulationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Postulation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': (new Date(json['date'])),
        'status': json['status'],
        'studentUser': json['student_user'],
        'coordinatorUser': json['coordinator_user'],
    };
}

export function PostulationToJSON(value?: Postulation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.date.toISOString()),
        'status': value.status,
        'student_user': value.studentUser,
        'coordinator_user': value.coordinatorUser,
    };
}

