/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostulationRequest
 */
export interface PostulationRequest {
    /**
     * 
     * @type {Date}
     * @memberof PostulationRequest
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof PostulationRequest
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof PostulationRequest
     */
    studentUser: number;
    /**
     * 
     * @type {number}
     * @memberof PostulationRequest
     */
    coordinatorUser: number;
}

/**
 * Check if a given object implements the PostulationRequest interface.
 */
export function instanceOfPostulationRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "studentUser" in value;
    isInstance = isInstance && "coordinatorUser" in value;

    return isInstance;
}

export function PostulationRequestFromJSON(json: any): PostulationRequest {
    return PostulationRequestFromJSONTyped(json, false);
}

export function PostulationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostulationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'status': json['status'],
        'studentUser': json['student_user'],
        'coordinatorUser': json['coordinator_user'],
    };
}

export function PostulationRequestToJSON(value?: PostulationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.date.toISOString()),
        'status': value.status,
        'student_user': value.studentUser,
        'coordinator_user': value.coordinatorUser,
    };
}

