/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TutorAreas } from './TutorAreas';
import {
    TutorAreasFromJSON,
    TutorAreasFromJSONTyped,
    TutorAreasToJSON,
} from './TutorAreas';

/**
 * 
 * @export
 * @interface ReadTutorUserSchedule
 */
export interface ReadTutorUserSchedule {
    /**
     * 
     * @type {number}
     * @memberof ReadTutorUserSchedule
     */
    readonly id: number;
    /**
     * 
     * @type {TutorAreas}
     * @memberof ReadTutorUserSchedule
     */
    tutorUser: TutorAreas;
    /**
     * 
     * @type {string}
     * @memberof ReadTutorUserSchedule
     */
    modality: string;
    /**
     * 
     * @type {string}
     * @memberof ReadTutorUserSchedule
     */
    day: string;
    /**
     * 
     * @type {string}
     * @memberof ReadTutorUserSchedule
     */
    begin: string;
    /**
     * 
     * @type {string}
     * @memberof ReadTutorUserSchedule
     */
    end: string;
    /**
     * 
     * @type {number}
     * @memberof ReadTutorUserSchedule
     */
    capacity: number;
}

/**
 * Check if a given object implements the ReadTutorUserSchedule interface.
 */
export function instanceOfReadTutorUserSchedule(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "tutorUser" in value;
    isInstance = isInstance && "modality" in value;
    isInstance = isInstance && "day" in value;
    isInstance = isInstance && "begin" in value;
    isInstance = isInstance && "end" in value;
    isInstance = isInstance && "capacity" in value;

    return isInstance;
}

export function ReadTutorUserScheduleFromJSON(json: any): ReadTutorUserSchedule {
    return ReadTutorUserScheduleFromJSONTyped(json, false);
}

export function ReadTutorUserScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadTutorUserSchedule {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tutorUser': TutorAreasFromJSON(json['tutor_user']),
        'modality': json['modality'],
        'day': json['day'],
        'begin': json['begin'],
        'end': json['end'],
        'capacity': json['capacity'],
    };
}

export function ReadTutorUserScheduleToJSON(value?: ReadTutorUserSchedule | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tutor_user': TutorAreasToJSON(value.tutorUser),
        'modality': value.modality,
        'day': value.day,
        'begin': value.begin,
        'end': value.end,
        'capacity': value.capacity,
    };
}

