/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ReturnAuthUser
 */
export interface ReturnAuthUser {
    /**
     * 
     * @type {User}
     * @memberof ReturnAuthUser
     */
    user: User;
    /**
     * 
     * @type {string}
     * @memberof ReturnAuthUser
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnAuthUser
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the ReturnAuthUser interface.
 */
export function instanceOfReturnAuthUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "refreshToken" in value;

    return isInstance;
}

export function ReturnAuthUserFromJSON(json: any): ReturnAuthUser {
    return ReturnAuthUserFromJSONTyped(json, false);
}

export function ReturnAuthUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnAuthUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserFromJSON(json['user']),
        'accessToken': json['access_token'],
        'refreshToken': json['refresh_token'],
    };
}

export function ReturnAuthUserToJSON(value?: ReturnAuthUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserToJSON(value.user),
        'access_token': value.accessToken,
        'refresh_token': value.refreshToken,
    };
}

