/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReturnRefreshToken
 */
export interface ReturnRefreshToken {
    /**
     * 
     * @type {string}
     * @memberof ReturnRefreshToken
     */
    access: string;
    /**
     * 
     * @type {string}
     * @memberof ReturnRefreshToken
     */
    refresh: string;
}

/**
 * Check if a given object implements the ReturnRefreshToken interface.
 */
export function instanceOfReturnRefreshToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "access" in value;
    isInstance = isInstance && "refresh" in value;

    return isInstance;
}

export function ReturnRefreshTokenFromJSON(json: any): ReturnRefreshToken {
    return ReturnRefreshTokenFromJSONTyped(json, false);
}

export function ReturnRefreshTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnRefreshToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'access': json['access'],
        'refresh': json['refresh'],
    };
}

export function ReturnRefreshTokenToJSON(value?: ReturnRefreshToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access': value.access,
        'refresh': value.refresh,
    };
}

