/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadTutorUserSchedule } from './ReadTutorUserSchedule';
import {
    ReadTutorUserScheduleFromJSON,
    ReadTutorUserScheduleFromJSONTyped,
    ReadTutorUserScheduleToJSON,
} from './ReadTutorUserSchedule';

/**
 * 
 * @export
 * @interface SearchTutorship
 */
export interface SearchTutorship {
    /**
     * 
     * @type {ReadTutorUserSchedule}
     * @memberof SearchTutorship
     */
    schedule: ReadTutorUserSchedule;
    /**
     * 
     * @type {Date}
     * @memberof SearchTutorship
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof SearchTutorship
     */
    area: string;
    /**
     * 
     * @type {string}
     * @memberof SearchTutorship
     */
    status: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof SearchTutorship
     */
    readonly users: Array<number>;
}

/**
 * Check if a given object implements the SearchTutorship interface.
 */
export function instanceOfSearchTutorship(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "schedule" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "area" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function SearchTutorshipFromJSON(json: any): SearchTutorship {
    return SearchTutorshipFromJSONTyped(json, false);
}

export function SearchTutorshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTutorship {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schedule': ReadTutorUserScheduleFromJSON(json['schedule']),
        'date': (new Date(json['date'])),
        'area': json['area'],
        'status': json['status'],
        'users': json['users'],
    };
}

export function SearchTutorshipToJSON(value?: SearchTutorship | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schedule': ReadTutorUserScheduleToJSON(value.schedule),
        'date': (value.date.toISOString().substring(0,10)),
        'area': value.area,
        'status': value.status,
    };
}

