/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagRequest
 */
export interface TagRequest {
    /**
     * 
     * @type {string}
     * @memberof TagRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof TagRequest
     */
    area: number;
}

/**
 * Check if a given object implements the TagRequest interface.
 */
export function instanceOfTagRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "area" in value;

    return isInstance;
}

export function TagRequestFromJSON(json: any): TagRequest {
    return TagRequestFromJSONTyped(json, false);
}

export function TagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'area': json['area'],
    };
}

export function TagRequestToJSON(value?: TagRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'area': value.area,
    };
}

