/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TutorshipReportRequest
 */
export interface TutorshipReportRequest {
    /**
     * 
     * @type {string}
     * @memberof TutorshipReportRequest
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof TutorshipReportRequest
     */
    subject: string;
    /**
     * 
     * @type {number}
     * @memberof TutorshipReportRequest
     */
    tutorshipInstance: number;
    /**
     * 
     * @type {number}
     * @memberof TutorshipReportRequest
     */
    tutorUser: number;
}

/**
 * Check if a given object implements the TutorshipReportRequest interface.
 */
export function instanceOfTutorshipReportRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "comment" in value;
    isInstance = isInstance && "subject" in value;
    isInstance = isInstance && "tutorshipInstance" in value;
    isInstance = isInstance && "tutorUser" in value;

    return isInstance;
}

export function TutorshipReportRequestFromJSON(json: any): TutorshipReportRequest {
    return TutorshipReportRequestFromJSONTyped(json, false);
}

export function TutorshipReportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TutorshipReportRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'subject': json['subject'],
        'tutorshipInstance': json['tutorship_instance'],
        'tutorUser': json['tutor_user'],
    };
}

export function TutorshipReportRequestToJSON(value?: TutorshipReportRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'subject': value.subject,
        'tutorship_instance': value.tutorshipInstance,
        'tutor_user': value.tutorUser,
    };
}

