/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TutorshipReport
 */
export interface TutorshipReport {
    /**
     * 
     * @type {number}
     * @memberof TutorshipReport
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof TutorshipReport
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof TutorshipReport
     */
    subject: string;
    /**
     * 
     * @type {number}
     * @memberof TutorshipReport
     */
    tutorshipInstance: number;
    /**
     * 
     * @type {number}
     * @memberof TutorshipReport
     */
    tutorUser: number;
}

/**
 * Check if a given object implements the TutorshipReport interface.
 */
export function instanceOfTutorshipReport(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "comment" in value;
    isInstance = isInstance && "subject" in value;
    isInstance = isInstance && "tutorshipInstance" in value;
    isInstance = isInstance && "tutorUser" in value;

    return isInstance;
}

export function TutorshipReportFromJSON(json: any): TutorshipReport {
    return TutorshipReportFromJSONTyped(json, false);
}

export function TutorshipReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): TutorshipReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'comment': json['comment'],
        'subject': json['subject'],
        'tutorshipInstance': json['tutorship_instance'],
        'tutorUser': json['tutor_user'],
    };
}

export function TutorshipReportToJSON(value?: TutorshipReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': value.comment,
        'subject': value.subject,
        'tutorship_instance': value.tutorshipInstance,
        'tutor_user': value.tutorUser,
    };
}

