/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TutorAreasRequest
 */
export interface TutorAreasRequest {
    /**
     * 
     * @type {string}
     * @memberof TutorAreasRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof TutorAreasRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof TutorAreasRequest
     */
    profilePicture?: string | null;
}

/**
 * Check if a given object implements the TutorAreasRequest interface.
 */
export function instanceOfTutorAreasRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TutorAreasRequestFromJSON(json: any): TutorAreasRequest {
    return TutorAreasRequestFromJSONTyped(json, false);
}

export function TutorAreasRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TutorAreasRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'profilePicture': !exists(json, 'profile_picture') ? undefined : json['profile_picture'],
    };
}

export function TutorAreasRequestToJSON(value?: TutorAreasRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'last_name': value.lastName,
        'profile_picture': value.profilePicture,
    };
}

