/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TutorshipInstance
 */
export interface TutorshipInstance {
    /**
     * 
     * @type {number}
     * @memberof TutorshipInstance
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof TutorshipInstance
     */
    area: string;
    /**
     * 
     * @type {number}
     * @memberof TutorshipInstance
     */
    schedule: number;
    /**
     * 
     * @type {Date}
     * @memberof TutorshipInstance
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof TutorshipInstance
     */
    status: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof TutorshipInstance
     */
    readonly users: Array<number>;
}

/**
 * Check if a given object implements the TutorshipInstance interface.
 */
export function instanceOfTutorshipInstance(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "area" in value;
    isInstance = isInstance && "schedule" in value;
    isInstance = isInstance && "date" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "users" in value;

    return isInstance;
}

export function TutorshipInstanceFromJSON(json: any): TutorshipInstance {
    return TutorshipInstanceFromJSONTyped(json, false);
}

export function TutorshipInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TutorshipInstance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'area': json['area'],
        'schedule': json['schedule'],
        'date': (new Date(json['date'])),
        'status': json['status'],
        'users': json['users'],
    };
}

export function TutorshipInstanceToJSON(value?: TutorshipInstance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'area': value.area,
        'schedule': value.schedule,
        'date': (value.date.toISOString().substring(0,10)),
        'status': value.status,
    };
}

