/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserXAreaRequest
 */
export interface UserXAreaRequest {
    /**
     * 
     * @type {number}
     * @memberof UserXAreaRequest
     */
    user: number;
    /**
     * 
     * @type {number}
     * @memberof UserXAreaRequest
     */
    area: number;
}

/**
 * Check if a given object implements the UserXAreaRequest interface.
 */
export function instanceOfUserXAreaRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "area" in value;

    return isInstance;
}

export function UserXAreaRequestFromJSON(json: any): UserXAreaRequest {
    return UserXAreaRequestFromJSONTyped(json, false);
}

export function UserXAreaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserXAreaRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': json['user'],
        'area': json['area'],
    };
}

export function UserXAreaRequestToJSON(value?: UserXAreaRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
        'area': value.area,
    };
}

