/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRequest
 */
export interface UserRequest {
    /**
     * 
     * @type {number}
     * @memberof UserRequest
     */
    uccKey: number;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRequest
     */
    profilePicture?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserRequest
     */
    academicYear: number;
}

/**
 * Check if a given object implements the UserRequest interface.
 */
export function instanceOfUserRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "uccKey" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "academicYear" in value;

    return isInstance;
}

export function UserRequestFromJSON(json: any): UserRequest {
    return UserRequestFromJSONTyped(json, false);
}

export function UserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uccKey': json['ucc_key'],
        'email': json['email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'profilePicture': !exists(json, 'profile_picture') ? undefined : json['profile_picture'],
        'academicYear': json['academic_year'],
    };
}

export function UserRequestToJSON(value?: UserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ucc_key': value.uccKey,
        'email': value.email,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'profile_picture': value.profilePicture,
        'academic_year': value.academicYear,
    };
}

