/* tslint:disable */
/* eslint-disable */
/**
 * Turnero TAIE API
 * API correspondiente al trabajo final \"Turnero TAIE\", realizado por los alumnos Juan Manuel Villarreal y Ghilino Ramiro
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserXTutorshipInstanceXRoleRequest
 */
export interface UserXTutorshipInstanceXRoleRequest {
    /**
     * 
     * @type {number}
     * @memberof UserXTutorshipInstanceXRoleRequest
     */
    user: number;
    /**
     * 
     * @type {number}
     * @memberof UserXTutorshipInstanceXRoleRequest
     */
    tutorshipInstance: number;
    /**
     * 
     * @type {number}
     * @memberof UserXTutorshipInstanceXRoleRequest
     */
    role: number;
}

/**
 * Check if a given object implements the UserXTutorshipInstanceXRoleRequest interface.
 */
export function instanceOfUserXTutorshipInstanceXRoleRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "user" in value;
    isInstance = isInstance && "tutorshipInstance" in value;
    isInstance = isInstance && "role" in value;

    return isInstance;
}

export function UserXTutorshipInstanceXRoleRequestFromJSON(json: any): UserXTutorshipInstanceXRoleRequest {
    return UserXTutorshipInstanceXRoleRequestFromJSONTyped(json, false);
}

export function UserXTutorshipInstanceXRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserXTutorshipInstanceXRoleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': json['user'],
        'tutorshipInstance': json['tutorship_instance'],
        'role': json['role'],
    };
}

export function UserXTutorshipInstanceXRoleRequestToJSON(value?: UserXTutorshipInstanceXRoleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
        'tutorship_instance': value.tutorshipInstance,
        'role': value.role,
    };
}

